#!/usr/bin/env perl
use strict;
use warnings;

use FindBin;
use Getopt::Long;

use lib "$FindBin::RealBin/../lib";

#--------------------------------------------------------------------------------
#----------------------------------- MAIN ---------------------------------------
#--------------------------------------------------------------------------------

my $usage = "

Description:

artemisia - tools for hacking genomics data

Commands:

    help              Show this message and exit.

    view              View data.

";


# Dispatch command
#--------------------------------------------------------------------------------

my $command = shift @ARGV || '';

if (! $command) {
    die "$usage\n\nFATAL : missing_command : You must provide a command to ugp_db2\n";
}
elsif ($command eq 'view') {
    command_view();
}
else {
    die "$usage\n\nFATAL : unknown_command : $command\n";
}

#--------------------------------------------------------------------------------
#------------------------------------ VIEW ------------------------------------
#--------------------------------------------------------------------------------

sub command_view {

      my $usage = "

Synopsis:

  artemisia view gff3 genes.gff3

Description:

  View GFF3 data files.

Options:

";

      my ($help);
      my %opt = (help        => \$help,
	  );

      my $opt_success = GetOptions(\%opt,
				   'help|h',
				   'select|s=s',
				   'from|f=s',
				   'where|w=s',
				   'where_value|v=s',
	  );

      if ($help) {
	  print $usage;
	  exit(0);
      }

      die $usage if ! $opt_success;

}

#--------------------------------------------------------------------------------

sub view_gff3 {

    my ($args) = shift @_;

}

#--------------------------------------------------------------------------------
[bm
